# Generated by Django 4.0.4 on 2022-06-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_bids_city_comments_alter_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='f',
        ),
    ]
