# Generated by Django 4.0.4 on 2022-06-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
