# Generated by Django 4.0.4 on 2022-06-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_category_auction_listings_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('al', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_listings', to='auctions.auction_listings')),
            ],
        ),
    ]
