# Generated by Django 4.0.4 on 2022-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='al',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='al',
            field=models.ManyToManyField(blank=True, related_name='auction_listings', to='auctions.auction_listings'),
        ),
    ]
