# Generated by Django 4.0.4 on 2022-06-04 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_watchlist_al_watchlist_al'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='al',
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('al', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listings')),
            ],
        ),
        migrations.AddField(
            model_name='watchlist',
            name='als',
            field=models.ManyToManyField(to='auctions.watchlistitem'),
        ),
    ]
