# Generated by Django 4.0.4 on 2022-06-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_watchlistitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlistitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
